#!/usr/bin/env python3
"""
config 包 - 项目统一配置中心
=============================
从此处导入所有配置，确保单一真相源。

使用方式:
    from config import DB_PATH, TOOLS_DIR, DIFFERENTIATED_DIR
    from config import GITHUB_REPOS, is_free_skill
    from config import get_db_connection
"""

# 路径与常量
from project_config import (
    PROJECT_ROOT, DB_PATH,
    TOOLS_DIR, REGISTRY_DIR, DATA_DIR,
    PACKAGED_SKILLS_DIR, HERMES_SKILLS_DIR, OPENSOURCE_SKILLS_DIR,
    ENTERPRISE_UPLOAD_DIR, CLAWHUB_DOWNLOADED_DIR, DIFFERENTIATED_DIR,
    REPORT_DIR, MARKET_DATA_DIR, BACKUP_DIR, DISCOVERY_DIR,
    HEALTH_REPORT_DIR, EXPORT_DIR, CREDENTIALS_DIR,
    # 阈值
    TRACE_PASS_THRESHOLD, TRACE_GRADE_A_PLUS, TRACE_GRADE_A,
    TRACE_GRADE_B, TRACE_GRADE_C,
    L2_PASS_THRESHOLD, L2_EXCELLENT_THRESHOLD, L2_MANUAL_REVIEW_THRESHOLD,
    L3_PASS_THRESHOLD,
    MIN_TRACE_SCORE, MAX_SKILL_MD_LINES, MIN_SKILL_MD_LINES,
    MIN_DESCRIPTION_LEN, MAX_DESCRIPTION_LEN,
    MAX_DISPLAYNAME_LEN, MIN_SUMMARY_LEN, MAX_SUMMARY_LEN,
    # 付费判断
    PAID_LICENSE_KEYWORDS, PAID_EDITION_KEYWORDS, OPEN_LICENSE_KEYWORDS,
    # 表名
    SCORE_TYPE_TRACE_LLM, SCORE_TYPE_BASELINE,
    # 映射
    TRACE_FIELD_MAPPING,
    # 安全
    MAX_SCAN_PAGES, BATCH_BACKUP_ENABLED,
    # 定价
    MIN_PRICE, MAX_PRICE,
    # 函数
    get_db_connection, is_paid_skill, safe_float, safe_int,
    create_backup, ensure_config_in_path,
)

# 平台配置
from platform_config import (
    # SkillHub
    SKILLHUB_CLI_PATH, SKILLHUB_API_URL, SKILLHUB_WAF_CHAR_LIMIT,
    SKILLHUB_PUBLISH_COMMAND, SKILLHUB_CREDENTIALS_FILE, SKILLHUB_MAX_RETRIES,
    SKILLHUB_STATUSES,
    # ClawHub
    CLAWHUB_CLI_PATH, CLAWHUB_API_URL, CLAWHUB_DAILY_UPLOAD_LIMIT,
    CLAWHUB_RATE_LIMIT_HOURS, CLAWHUB_TOKEN_FILE, CLAWHUB_PUBLISH_COMMAND,
    CLAWHUB_PROTECTED_PREFIX,
    # GitHub
    GITHUB_PUBLIC_REMOTE, GITHUB_PUBLIC_REPO_URL, GITHUB_PUBLIC_VISIBILITY,
    GITHUB_PRIVATE_REMOTE, GITHUB_PRIVATE_REPO_URL, GITHUB_PRIVATE_VISIBILITY,
    GITHUB_BRANCH,
    FREE_PRICING_VALUES, FREE_PRICING_TIERS, FREE_LICENSES,
    PAID_PRICING_TIERS, PAID_LICENSES,
    GITHUB_REPOS,
    # 函数
    is_free_skill as is_free_skill_platform,
    get_push_strategy,
)

# 便捷别名：is_free_skill（平台版，用于GitHub仓库判定）
is_free_skill = is_free_skill_platform

__all__ = [
    # 路径
    'PROJECT_ROOT', 'DB_PATH', 'TOOLS_DIR', 'REGISTRY_DIR', 'DATA_DIR',
    'PACKAGED_SKILLS_DIR', 'HERMES_SKILLS_DIR', 'OPENSOURCE_SKILLS_DIR',
    'ENTERPRISE_UPLOAD_DIR', 'CLAWHUB_DOWNLOADED_DIR', 'DIFFERENTIATED_DIR',
    'REPORT_DIR', 'MARKET_DATA_DIR', 'BACKUP_DIR', 'DISCOVERY_DIR',
    'HEALTH_REPORT_DIR', 'EXPORT_DIR', 'CREDENTIALS_DIR',
    # 阈值
    'TRACE_PASS_THRESHOLD', 'TRACE_GRADE_A_PLUS', 'TRACE_GRADE_A',
    'TRACE_GRADE_B', 'TRACE_GRADE_C',
    'L2_PASS_THRESHOLD', 'L2_EXCELLENT_THRESHOLD', 'L2_MANUAL_REVIEW_THRESHOLD',
    'L3_PASS_THRESHOLD',
    'MIN_TRACE_SCORE', 'MAX_SKILL_MD_LINES', 'MIN_SKILL_MD_LINES',
    'MIN_DESCRIPTION_LEN', 'MAX_DESCRIPTION_LEN',
    'MAX_DISPLAYNAME_LEN', 'MIN_SUMMARY_LEN', 'MAX_SUMMARY_LEN',
    # 付费
    'PAID_LICENSE_KEYWORDS', 'PAID_EDITION_KEYWORDS', 'OPEN_LICENSE_KEYWORDS',
    # 表名
    'SCORE_TYPE_TRACE_LLM', 'SCORE_TYPE_BASELINE',
    # 映射
    'TRACE_FIELD_MAPPING',
    # 安全
    'MAX_SCAN_PAGES', 'BATCH_BACKUP_ENABLED',
    # 定价
    'MIN_PRICE', 'MAX_PRICE',
    # 函数
    'get_db_connection', 'is_paid_skill', 'is_free_skill', 'get_push_strategy',
    'safe_float', 'safe_int', 'create_backup', 'ensure_config_in_path',
    # 平台
    'SKILLHUB_CLI_PATH', 'SKILLHUB_API_URL', 'SKILLHUB_WAF_CHAR_LIMIT',
    'SKILLHUB_PUBLISH_COMMAND', 'SKILLHUB_CREDENTIALS_FILE', 'SKILLHUB_MAX_RETRIES',
    'SKILLHUB_STATUSES',
    'CLAWHUB_CLI_PATH', 'CLAWHUB_API_URL', 'CLAWHUB_DAILY_UPLOAD_LIMIT',
    'CLAWHUB_RATE_LIMIT_HOURS', 'CLAWHUB_TOKEN_FILE', 'CLAWHUB_PUBLISH_COMMAND',
    'CLAWHUB_PROTECTED_PREFIX',
    'GITHUB_PUBLIC_REMOTE', 'GITHUB_PUBLIC_REPO_URL', 'GITHUB_PUBLIC_VISIBILITY',
    'GITHUB_PRIVATE_REMOTE', 'GITHUB_PRIVATE_REPO_URL', 'GITHUB_PRIVATE_VISIBILITY',
    'GITHUB_BRANCH', 'GITHUB_REPOS',
    'FREE_PRICING_VALUES', 'FREE_PRICING_TIERS', 'FREE_LICENSES',
    'PAID_PRICING_TIERS', 'PAID_LICENSES',
]
